// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TimeStamp struct {
	Seconds              int64    `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos                int32    `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeStamp) Reset()         { *m = TimeStamp{} }
func (m *TimeStamp) String() string { return proto.CompactTextString(m) }
func (*TimeStamp) ProtoMessage()    {}
func (*TimeStamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *TimeStamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeStamp.Unmarshal(m, b)
}
func (m *TimeStamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeStamp.Marshal(b, m, deterministic)
}
func (m *TimeStamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeStamp.Merge(m, src)
}
func (m *TimeStamp) XXX_Size() int {
	return xxx_messageInfo_TimeStamp.Size(m)
}
func (m *TimeStamp) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeStamp.DiscardUnknown(m)
}

var xxx_messageInfo_TimeStamp proto.InternalMessageInfo

func (m *TimeStamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *TimeStamp) GetNanos() int32 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

type TaskMessage struct {
	Time                 *TimeStamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	PartnerId            int64      `protobuf:"varint,2,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TaskMessage) Reset()         { *m = TaskMessage{} }
func (m *TaskMessage) String() string { return proto.CompactTextString(m) }
func (*TaskMessage) ProtoMessage()    {}
func (*TaskMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *TaskMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskMessage.Unmarshal(m, b)
}
func (m *TaskMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskMessage.Marshal(b, m, deterministic)
}
func (m *TaskMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskMessage.Merge(m, src)
}
func (m *TaskMessage) XXX_Size() int {
	return xxx_messageInfo_TaskMessage.Size(m)
}
func (m *TaskMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TaskMessage proto.InternalMessageInfo

func (m *TaskMessage) GetTime() *TimeStamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *TaskMessage) GetPartnerId() int64 {
	if m != nil {
		return m.PartnerId
	}
	return 0
}

type Counter struct {
	Revenue              int64    `protobuf:"varint,1,opt,name=revenue,proto3" json:"revenue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Counter) Reset()         { *m = Counter{} }
func (m *Counter) String() string { return proto.CompactTextString(m) }
func (*Counter) ProtoMessage()    {}
func (*Counter) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2}
}

func (m *Counter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Counter.Unmarshal(m, b)
}
func (m *Counter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Counter.Marshal(b, m, deterministic)
}
func (m *Counter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Counter.Merge(m, src)
}
func (m *Counter) XXX_Size() int {
	return xxx_messageInfo_Counter.Size(m)
}
func (m *Counter) XXX_DiscardUnknown() {
	xxx_messageInfo_Counter.DiscardUnknown(m)
}

var xxx_messageInfo_Counter proto.InternalMessageInfo

func (m *Counter) GetRevenue() int64 {
	if m != nil {
		return m.Revenue
	}
	return 0
}

type StatsReq struct {
	PartnerId            int64    `protobuf:"varint,1,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatsReq) Reset()         { *m = StatsReq{} }
func (m *StatsReq) String() string { return proto.CompactTextString(m) }
func (*StatsReq) ProtoMessage()    {}
func (*StatsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{3}
}

func (m *StatsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsReq.Unmarshal(m, b)
}
func (m *StatsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsReq.Marshal(b, m, deterministic)
}
func (m *StatsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsReq.Merge(m, src)
}
func (m *StatsReq) XXX_Size() int {
	return xxx_messageInfo_StatsReq.Size(m)
}
func (m *StatsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsReq.DiscardUnknown(m)
}

var xxx_messageInfo_StatsReq proto.InternalMessageInfo

func (m *StatsReq) GetPartnerId() int64 {
	if m != nil {
		return m.PartnerId
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{4}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TimeStamp)(nil), "api.TimeStamp")
	proto.RegisterType((*TaskMessage)(nil), "api.TaskMessage")
	proto.RegisterType((*Counter)(nil), "api.Counter")
	proto.RegisterType((*StatsReq)(nil), "api.StatsReq")
	proto.RegisterType((*Empty)(nil), "api.Empty")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x1b, 0x63, 0x9a, 0x76, 0xaa, 0x22, 0x8b, 0x87, 0x50, 0x10, 0xca, 0x7a, 0x49, 0x2f,
	0x39, 0xd4, 0xa3, 0x47, 0x11, 0xf1, 0x20, 0xc8, 0xb6, 0x77, 0x19, 0x9b, 0x41, 0x16, 0xc9, 0xee,
	0xba, 0x3b, 0x15, 0xfc, 0xf7, 0xd2, 0x69, 0x62, 0xa1, 0xc7, 0x37, 0xc3, 0xfb, 0xe6, 0xdb, 0x05,
	0x68, 0x91, 0xb1, 0x09, 0xd1, 0xb3, 0x57, 0x39, 0x06, 0xab, 0x1f, 0x60, 0xba, 0xb1, 0x1d, 0xad,
	0x19, 0xbb, 0xa0, 0x2a, 0x28, 0x13, 0x6d, 0xbd, 0x6b, 0x53, 0x95, 0x2d, 0xb2, 0x3a, 0x37, 0x43,
	0x54, 0x37, 0x50, 0x38, 0x74, 0x3e, 0x55, 0x67, 0x8b, 0xac, 0x2e, 0xcc, 0x21, 0xe8, 0x37, 0x98,
	0x6d, 0x30, 0x7d, 0xbd, 0x52, 0x4a, 0xf8, 0x49, 0x4a, 0xc3, 0x39, 0xdb, 0x8e, 0xa4, 0x3b, 0x5b,
	0x5d, 0x35, 0x18, 0x6c, 0xf3, 0x0f, 0x37, 0xb2, 0x53, 0xb7, 0x00, 0x01, 0x23, 0x3b, 0x8a, 0xef,
	0xb6, 0x15, 0x5a, 0x6e, 0xa6, 0xfd, 0xe4, 0xa5, 0xd5, 0x77, 0x50, 0x3e, 0xfa, 0x9d, 0x63, 0x8a,
	0x7b, 0x99, 0x48, 0x3f, 0xe4, 0x76, 0x34, 0xc8, 0xf4, 0x51, 0x2f, 0x61, 0xb2, 0x66, 0xe4, 0x64,
	0xe8, 0xfb, 0x84, 0x97, 0x9d, 0xf2, 0x4a, 0x28, 0x9e, 0xba, 0xc0, 0xbf, 0x2b, 0x04, 0xd8, 0x77,
	0x6c, 0x62, 0xbb, 0x4d, 0xaa, 0x86, 0xb1, 0xa1, 0xe0, 0x23, 0xab, 0xeb, 0x83, 0xe5, 0xf1, 0x15,
	0x73, 0x90, 0x89, 0xb4, 0xf4, 0x48, 0x2d, 0x61, 0xf2, 0x4c, 0x2c, 0xe7, 0xd4, 0xa5, 0x6c, 0x86,
	0xd3, 0xf3, 0x0b, 0x89, 0xbd, 0xae, 0x1e, 0x7d, 0x8c, 0xe5, 0x5b, 0xef, 0xff, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x0e, 0x6e, 0xee, 0x8f, 0x64, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StatisticsClient is the client API for Statistics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatisticsClient interface {
	Report(ctx context.Context, in *TaskMessage, opts ...grpc.CallOption) (*Empty, error)
	GetStats(ctx context.Context, in *StatsReq, opts ...grpc.CallOption) (*Counter, error)
}

type statisticsClient struct {
	cc *grpc.ClientConn
}

func NewStatisticsClient(cc *grpc.ClientConn) StatisticsClient {
	return &statisticsClient{cc}
}

func (c *statisticsClient) Report(ctx context.Context, in *TaskMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.Statistics/Report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsClient) GetStats(ctx context.Context, in *StatsReq, opts ...grpc.CallOption) (*Counter, error) {
	out := new(Counter)
	err := c.cc.Invoke(ctx, "/api.Statistics/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticsServer is the server API for Statistics service.
type StatisticsServer interface {
	Report(context.Context, *TaskMessage) (*Empty, error)
	GetStats(context.Context, *StatsReq) (*Counter, error)
}

func RegisterStatisticsServer(s *grpc.Server, srv StatisticsServer) {
	s.RegisterService(&_Statistics_serviceDesc, srv)
}

func _Statistics_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Statistics/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).Report(ctx, req.(*TaskMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Statistics_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Statistics/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).GetStats(ctx, req.(*StatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Statistics_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Statistics",
	HandlerType: (*StatisticsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Report",
			Handler:    _Statistics_Report_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _Statistics_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data.proto",
}
