// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TaskMessage struct {
	Date                 string   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	EventId              int64    `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	PartnerId            int64    `protobuf:"varint,4,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskMessage) Reset()         { *m = TaskMessage{} }
func (m *TaskMessage) String() string { return proto.CompactTextString(m) }
func (*TaskMessage) ProtoMessage()    {}
func (*TaskMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_a63f2357132c6d58, []int{0}
}
func (m *TaskMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskMessage.Unmarshal(m, b)
}
func (m *TaskMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskMessage.Marshal(b, m, deterministic)
}
func (dst *TaskMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskMessage.Merge(dst, src)
}
func (m *TaskMessage) XXX_Size() int {
	return xxx_messageInfo_TaskMessage.Size(m)
}
func (m *TaskMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TaskMessage proto.InternalMessageInfo

func (m *TaskMessage) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *TaskMessage) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *TaskMessage) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *TaskMessage) GetPartnerId() int64 {
	if m != nil {
		return m.PartnerId
	}
	return 0
}

type Counter struct {
	Revenue              int64    `protobuf:"varint,1,opt,name=revenue,proto3" json:"revenue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Counter) Reset()         { *m = Counter{} }
func (m *Counter) String() string { return proto.CompactTextString(m) }
func (*Counter) ProtoMessage()    {}
func (*Counter) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_a63f2357132c6d58, []int{1}
}
func (m *Counter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Counter.Unmarshal(m, b)
}
func (m *Counter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Counter.Marshal(b, m, deterministic)
}
func (dst *Counter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Counter.Merge(dst, src)
}
func (m *Counter) XXX_Size() int {
	return xxx_messageInfo_Counter.Size(m)
}
func (m *Counter) XXX_DiscardUnknown() {
	xxx_messageInfo_Counter.DiscardUnknown(m)
}

var xxx_messageInfo_Counter proto.InternalMessageInfo

func (m *Counter) GetRevenue() int64 {
	if m != nil {
		return m.Revenue
	}
	return 0
}

func init() {
	proto.RegisterType((*TaskMessage)(nil), "api.TaskMessage")
	proto.RegisterType((*Counter)(nil), "api.Counter")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StatisticsClient is the client API for Statistics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatisticsClient interface {
	GetStatistics(ctx context.Context, in *TaskMessage, opts ...grpc.CallOption) (*TaskMessage, error)
}

type statisticsClient struct {
	cc *grpc.ClientConn
}

func NewStatisticsClient(cc *grpc.ClientConn) StatisticsClient {
	return &statisticsClient{cc}
}

func (c *statisticsClient) GetStatistics(ctx context.Context, in *TaskMessage, opts ...grpc.CallOption) (*TaskMessage, error) {
	out := new(TaskMessage)
	err := c.cc.Invoke(ctx, "/api.Statistics/GetStatistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticsServer is the server API for Statistics service.
type StatisticsServer interface {
	GetStatistics(context.Context, *TaskMessage) (*TaskMessage, error)
}

func RegisterStatisticsServer(s *grpc.Server, srv StatisticsServer) {
	s.RegisterService(&_Statistics_serviceDesc, srv)
}

func _Statistics_GetStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).GetStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Statistics/GetStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).GetStatistics(ctx, req.(*TaskMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Statistics_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Statistics",
	HandlerType: (*StatisticsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatistics",
			Handler:    _Statistics_GetStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data.proto",
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_data_a63f2357132c6d58) }

var fileDescriptor_data_a63f2357132c6d58 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xb1, 0x6a, 0xc3, 0x30,
	0x10, 0x86, 0xeb, 0xca, 0xd4, 0xf5, 0x95, 0x42, 0xd1, 0xa4, 0x16, 0x0a, 0xc6, 0x5d, 0x3c, 0x79,
	0x68, 0xe9, 0x13, 0x78, 0x08, 0x1e, 0xb2, 0x38, 0xd9, 0xc3, 0x25, 0x3a, 0x82, 0x08, 0xb1, 0x84,
	0x74, 0xce, 0xf3, 0x07, 0xc9, 0x09, 0x18, 0xb2, 0xfd, 0xff, 0xf7, 0x71, 0xdc, 0x1d, 0x80, 0x46,
	0xc6, 0xd6, 0x79, 0xcb, 0x56, 0x0a, 0x74, 0xa6, 0xb6, 0xf0, 0xb6, 0xc5, 0x70, 0x5a, 0x53, 0x08,
	0x78, 0x24, 0x29, 0x21, 0xd7, 0xc8, 0xa4, 0xb2, 0x2a, 0x6b, 0xca, 0x21, 0xe5, 0xc8, 0xd8, 0x9c,
	0x49, 0x3d, 0xcf, 0x2c, 0x66, 0xf9, 0x09, 0xaf, 0x74, 0xa1, 0x91, 0x77, 0x46, 0x2b, 0x51, 0x65,
	0x8d, 0x18, 0x8a, 0xd4, 0x7b, 0x2d, 0xbf, 0x01, 0x1c, 0x7a, 0x1e, 0xc9, 0x47, 0x99, 0x27, 0x59,
	0xde, 0x48, 0xaf, 0xeb, 0x1f, 0x28, 0x3a, 0x3b, 0x8d, 0x4c, 0x5e, 0x2a, 0x28, 0x7c, 0x9c, 0x9a,
	0xe6, 0x7d, 0x62, 0xb8, 0xd7, 0xdf, 0x0e, 0x60, 0xc3, 0xc8, 0x26, 0xb0, 0x39, 0x04, 0xf9, 0x0f,
	0xef, 0x2b, 0xe2, 0x05, 0xf8, 0x68, 0xd1, 0x99, 0x76, 0x71, 0xf7, 0xd7, 0x03, 0xa9, 0x9f, 0xf6,
	0x2f, 0xe9, 0xcd, 0xbf, 0x6b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x18, 0x76, 0xc7, 0xf4, 0x00,
	0x00, 0x00,
}
