// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TimeStamp struct {
	Seconds              int32    `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos                int64    `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeStamp) Reset()         { *m = TimeStamp{} }
func (m *TimeStamp) String() string { return proto.CompactTextString(m) }
func (*TimeStamp) ProtoMessage()    {}
func (*TimeStamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_803178afdc83ba99, []int{0}
}
func (m *TimeStamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeStamp.Unmarshal(m, b)
}
func (m *TimeStamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeStamp.Marshal(b, m, deterministic)
}
func (dst *TimeStamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeStamp.Merge(dst, src)
}
func (m *TimeStamp) XXX_Size() int {
	return xxx_messageInfo_TimeStamp.Size(m)
}
func (m *TimeStamp) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeStamp.DiscardUnknown(m)
}

var xxx_messageInfo_TimeStamp proto.InternalMessageInfo

func (m *TimeStamp) GetSeconds() int32 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *TimeStamp) GetNanos() int64 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

type TaskMessage struct {
	Date                 int64      `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
	Time                 *TimeStamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	PartnerId            int64      `protobuf:"varint,3,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TaskMessage) Reset()         { *m = TaskMessage{} }
func (m *TaskMessage) String() string { return proto.CompactTextString(m) }
func (*TaskMessage) ProtoMessage()    {}
func (*TaskMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_803178afdc83ba99, []int{1}
}
func (m *TaskMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskMessage.Unmarshal(m, b)
}
func (m *TaskMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskMessage.Marshal(b, m, deterministic)
}
func (dst *TaskMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskMessage.Merge(dst, src)
}
func (m *TaskMessage) XXX_Size() int {
	return xxx_messageInfo_TaskMessage.Size(m)
}
func (m *TaskMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TaskMessage proto.InternalMessageInfo

func (m *TaskMessage) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *TaskMessage) GetTime() *TimeStamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *TaskMessage) GetPartnerId() int64 {
	if m != nil {
		return m.PartnerId
	}
	return 0
}

type Counter struct {
	Revenue              int64    `protobuf:"varint,1,opt,name=revenue,proto3" json:"revenue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Counter) Reset()         { *m = Counter{} }
func (m *Counter) String() string { return proto.CompactTextString(m) }
func (*Counter) ProtoMessage()    {}
func (*Counter) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_803178afdc83ba99, []int{2}
}
func (m *Counter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Counter.Unmarshal(m, b)
}
func (m *Counter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Counter.Marshal(b, m, deterministic)
}
func (dst *Counter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Counter.Merge(dst, src)
}
func (m *Counter) XXX_Size() int {
	return xxx_messageInfo_Counter.Size(m)
}
func (m *Counter) XXX_DiscardUnknown() {
	xxx_messageInfo_Counter.DiscardUnknown(m)
}

var xxx_messageInfo_Counter proto.InternalMessageInfo

func (m *Counter) GetRevenue() int64 {
	if m != nil {
		return m.Revenue
	}
	return 0
}

type StatsReq struct {
	PartnerId            int64    `protobuf:"varint,1,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatsReq) Reset()         { *m = StatsReq{} }
func (m *StatsReq) String() string { return proto.CompactTextString(m) }
func (*StatsReq) ProtoMessage()    {}
func (*StatsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_803178afdc83ba99, []int{3}
}
func (m *StatsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsReq.Unmarshal(m, b)
}
func (m *StatsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsReq.Marshal(b, m, deterministic)
}
func (dst *StatsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsReq.Merge(dst, src)
}
func (m *StatsReq) XXX_Size() int {
	return xxx_messageInfo_StatsReq.Size(m)
}
func (m *StatsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsReq.DiscardUnknown(m)
}

var xxx_messageInfo_StatsReq proto.InternalMessageInfo

func (m *StatsReq) GetPartnerId() int64 {
	if m != nil {
		return m.PartnerId
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_803178afdc83ba99, []int{4}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TimeStamp)(nil), "api.TimeStamp")
	proto.RegisterType((*TaskMessage)(nil), "api.TaskMessage")
	proto.RegisterType((*Counter)(nil), "api.Counter")
	proto.RegisterType((*StatsReq)(nil), "api.StatsReq")
	proto.RegisterType((*Empty)(nil), "api.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StatisticsClient is the client API for Statistics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatisticsClient interface {
	Report(ctx context.Context, in *TaskMessage, opts ...grpc.CallOption) (*Empty, error)
	GetStats(ctx context.Context, in *StatsReq, opts ...grpc.CallOption) (*Counter, error)
}

type statisticsClient struct {
	cc *grpc.ClientConn
}

func NewStatisticsClient(cc *grpc.ClientConn) StatisticsClient {
	return &statisticsClient{cc}
}

func (c *statisticsClient) Report(ctx context.Context, in *TaskMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.Statistics/Report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsClient) GetStats(ctx context.Context, in *StatsReq, opts ...grpc.CallOption) (*Counter, error) {
	out := new(Counter)
	err := c.cc.Invoke(ctx, "/api.Statistics/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticsServer is the server API for Statistics service.
type StatisticsServer interface {
	Report(context.Context, *TaskMessage) (*Empty, error)
	GetStats(context.Context, *StatsReq) (*Counter, error)
}

func RegisterStatisticsServer(s *grpc.Server, srv StatisticsServer) {
	s.RegisterService(&_Statistics_serviceDesc, srv)
}

func _Statistics_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Statistics/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).Report(ctx, req.(*TaskMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Statistics_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Statistics/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).GetStats(ctx, req.(*StatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Statistics_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Statistics",
	HandlerType: (*StatisticsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Report",
			Handler:    _Statistics_Report_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _Statistics_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data.proto",
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_data_803178afdc83ba99) }

var fileDescriptor_data_803178afdc83ba99 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4b, 0x33, 0x31,
	0x10, 0xc5, 0xbb, 0xdf, 0x76, 0xbb, 0xed, 0xf4, 0x53, 0x24, 0x78, 0x58, 0x0a, 0x42, 0x89, 0x97,
	0xed, 0x65, 0x0f, 0xf5, 0xe8, 0x51, 0x44, 0x3c, 0x78, 0x49, 0x7b, 0x97, 0xb1, 0x19, 0x24, 0xc8,
	0x26, 0x31, 0x99, 0x0a, 0xfe, 0xf7, 0xd2, 0x69, 0x57, 0xa1, 0xb7, 0xbc, 0x19, 0x7e, 0xef, 0xbd,
	0x0c, 0x80, 0x45, 0xc6, 0x2e, 0xa6, 0xc0, 0x41, 0x95, 0x18, 0x9d, 0xbe, 0x87, 0xd9, 0xd6, 0xf5,
	0xb4, 0x61, 0xec, 0xa3, 0x6a, 0xa0, 0xce, 0xb4, 0x0b, 0xde, 0xe6, 0xa6, 0x58, 0x16, 0x6d, 0x65,
	0x06, 0xa9, 0xae, 0xa1, 0xf2, 0xe8, 0x43, 0x6e, 0xfe, 0x2d, 0x8b, 0xb6, 0x34, 0x47, 0xa1, 0x2d,
	0xcc, 0xb7, 0x98, 0x3f, 0x5e, 0x28, 0x67, 0x7c, 0x27, 0xa5, 0x60, 0x6c, 0x91, 0x49, 0xd8, 0xd2,
	0xc8, 0x5b, 0x69, 0x18, 0xb3, 0xeb, 0x49, 0xb8, 0xf9, 0xfa, 0xb2, 0xc3, 0xe8, 0xba, 0xdf, 0x40,
	0x23, 0x3b, 0x75, 0x03, 0x10, 0x31, 0xb1, 0xa7, 0xf4, 0xea, 0x6c, 0x53, 0x0a, 0x3d, 0x3b, 0x4d,
	0x9e, 0xad, 0xbe, 0x85, 0xfa, 0x21, 0xec, 0x3d, 0x53, 0x3a, 0x14, 0x4c, 0xf4, 0x45, 0x7e, 0x3f,
	0x84, 0x0c, 0x52, 0xaf, 0x60, 0xba, 0x61, 0xe4, 0x6c, 0xe8, 0xf3, 0xcc, 0xaf, 0x38, 0xf7, 0xab,
	0xa1, 0x7a, 0xec, 0x23, 0x7f, 0xaf, 0x11, 0xe0, 0xc0, 0xb8, 0xcc, 0x6e, 0x97, 0x55, 0x0b, 0x13,
	0x43, 0x31, 0x24, 0x56, 0x57, 0xc7, 0x96, 0x7f, 0x3f, 0x5b, 0x80, 0x4c, 0x84, 0xd2, 0x23, 0xb5,
	0x82, 0xe9, 0x13, 0xb1, 0xc4, 0xa9, 0x0b, 0xd9, 0x0c, 0xd1, 0x8b, 0xff, 0x22, 0x4f, 0x75, 0xf5,
	0xe8, 0x6d, 0x22, 0xa7, 0xbe, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xd3, 0x9c, 0xef, 0x78,
	0x01, 0x00, 0x00,
}
